window.MODA_DATA = {
  me: { name: 'Esty Moreau', role: 'Operations' },
  members: [
    { id: 'whitfield', photo: 'assets/photos/exterior-garden.jpg', name: 'Whitfield Residence', owners: 'Eleanor & James Whitfield', address: '14 Linden Crescent', tier: 'Signature', concierge: 'Esty Moreau', used: 1.5, allow: 2, next: 'Thu, Oct 9', renews: 'Mar 1, 2027', status: 'Active', since: 'Mar 2025', onsite: [{ d: 'Sep 24', who: 'Plumber — Hale & Sons', min: 75 }, { d: 'Sep 3', who: 'Electrician — Brightline', min: 50 }] },
    { id: 'ashby', photo: 'assets/photos/exterior-dusk.jpg', name: 'Ashby House', owners: 'Theo Ashby', address: '88 Beacon Hill Road', tier: 'Signature', concierge: 'Esty Moreau', used: 2, allow: 2, next: 'Tue, Oct 14', renews: 'Jun 15, 2027', status: 'Active', since: 'Jun 2025', onsite: [{ d: 'Oct 2', who: 'AV installer', min: 90 }] },
    { id: 'calloway', photo: 'assets/photos/living-neutral.jpg', name: 'Calloway Residence', owners: 'Margaret Calloway', address: '2 Orchard Lane', tier: 'Essential', concierge: 'Team', used: 0.5, allow: 1, next: 'Feb 12 (annual)', renews: 'Feb 1, 2027', status: 'Active', since: 'Feb 2025', onsite: [] },
    { id: 'delacroix', photo: 'assets/photos/exterior-modern.jpg', name: 'Delacroix Residence', owners: 'Simone & Paul Delacroix', address: '5 Willow Court', tier: 'Signature', concierge: 'Julian Hart', used: 0, allow: 2, next: 'Tue, Oct 21', renews: 'Aug 1, 2027', status: 'Active', since: 'Aug 2025', onsite: [] },
    { id: 'hartley', photo: 'assets/photos/living-open.jpg', name: 'Hartley House', owners: 'Owen Hartley', address: '31 Fairmount Avenue', tier: 'Essential', concierge: 'Team', used: 1, allow: 1, next: 'Apr 3 (annual)', renews: 'Apr 1, 2027', status: 'Active', since: 'Apr 2025', onsite: [] },
    { id: 'moreland', photo: 'assets/photos/staircase.jpg', name: 'Moreland Residence', owners: 'Clara Moreland', address: '9 Kingsley Place', tier: 'Signature', concierge: 'Julian Hart', used: 0, allow: 2, next: '—', renews: 'Nov 1, 2026', status: 'Paused', since: 'Nov 2024', onsite: [] },
  ],
  requests: [
    { id: 'R-218', via: 'Call', member: 'whitfield', title: 'Dishwasher leaking at door seal', type: 'Home issue', received: '6h ago', left: 18, status: 'New', assignee: null },
    { id: 'R-216', via: 'Text', member: 'hartley', title: 'Garage door opener intermittent', type: 'Home issue', received: '21h ago', left: 3, status: 'New', assignee: null },
    { id: 'R-217', via: 'Email', member: 'ashby', title: 'Mount 85-inch TV in media room', type: 'Handyman', received: 'Yesterday', left: null, status: 'Scheduled', assignee: 'Esty Moreau', when: 'Oct 14' },
    { id: 'R-215', via: 'Portal', member: 'calloway', title: 'Hang drapery in primary bedroom', type: 'Handyman', received: 'Oct 4', left: null, status: 'Responded', assignee: 'Julian Hart' },
    { id: 'R-214', via: 'Call', member: 'delacroix', title: 'Landscape lighting along drive', type: 'Project', received: 'Oct 1', left: null, status: 'Estimate sent', assignee: 'Julian Hart' },
    { id: 'R-210', via: 'Walk-through', member: 'whitfield', title: 'Replace HVAC filters', type: 'Handyman', received: 'Sep 24', left: null, status: 'Completed', assignee: 'Esty Moreau' },
  ],
  conversations: [
    { id: 'C-5012', channel: 'Call', member: 'hartley', from: 'Owen Hartley', when: '14 min ago', duration: '3m 41s', status: 'Needs a human', reason: 'Member asked to speak with a person about a billing dispute.',
      summary: 'Owen called about the garage door (R-216) and questioned the $125 on-site charge from September. Wants a person to review the invoice.',
      actions: ['Linked to request R-216', 'Pulled September statement', 'Promised a callback from the team today'],
      transcript: [['ai', 'Good afternoon, Moda Management — this is the Moda concierge. How can I help?'], ['member', 'Hi, it’s Owen Hartley. The garage door is still acting up, and I also want to ask about a charge on my last bill.'], ['ai', 'Of course, Mr. Hartley. I can see the garage door request from yesterday — a technician visit is being arranged. Which charge would you like to go over?'], ['member', 'The $125 on-site fee. I don’t remember agreeing to that. I’d rather talk to someone.'], ['ai', 'Understood. I’ll have a member of the team review the September invoice and call you back today. Is this number best?'], ['member', 'Yes, this number.'], ['ai', 'Thank you. You’ll hear from us this afternoon.']] },
    { id: 'C-5011', channel: 'Text', member: 'whitfield', from: 'Eleanor Whitfield', when: '1h ago', duration: '6 messages', status: 'Handled by AI', reason: '',
      summary: 'Eleanor asked if the handyman can hang a hallway mirror on Thursday. AI confirmed 0.5h remains and added it to the walk-through plan.',
      actions: ['Added “Hang hallway mirror” to Oct 9 visit', 'Confirmed 0.5h handyman time remaining'],
      transcript: [['member', 'Hi! Can the handyman hang the big mirror in our hallway on Thursday?'], ['ai', 'Certainly. You have 0.5 hours of handyman time left this month — enough for the mirror. I’ve added it to Thursday’s 10:00 visit.'], ['member', 'Perfect. It’s quite heavy, about 40lbs.'], ['ai', 'Noted — we’ll bring heavy-duty anchors and a second pair of hands. Anything else for Thursday?'], ['member', 'That’s all, thank you!'], ['ai', 'You’re welcome, Eleanor. See you Thursday.']] },
    { id: 'C-5010', channel: 'Call', member: 'whitfield', from: 'James Whitfield', when: '6h ago', duration: '2m 12s', status: 'Handled by AI', reason: '',
      summary: 'James reported a slow leak at the dishwasher door. AI walked him through shutting off the supply valve, logged R-218 and drafted estimate E-1042.',
      actions: ['Created request R-218', 'Drafted estimate E-1042 for review', 'Sent photo-upload link by text'],
      transcript: [['ai', 'Moda Management, this is the Moda concierge. How can I help?'], ['member', 'There’s water pooling under the dishwasher.'], ['ai', 'Thank you for calling. First, let’s stop the water — there should be a valve under the kitchen sink on the left. Could you turn it clockwise until it stops?'], ['member', 'Okay, done.'], ['ai', 'Well done. I’ve logged this and I’m texting you a link to send a photo of the door seal. We’ll arrange a technician and send an estimate before any work begins.']] },
    { id: 'C-5009', channel: 'Email', member: 'ashby', from: 'Theo Ashby', when: 'Yesterday', duration: '2 emails', status: 'Handled by AI', reason: '',
      summary: 'Theo asked to mount an 85-inch TV. AI checked hours (fully used) and scheduled for Oct 14 as billable on-site time, with confirmation.',
      actions: ['Created request R-217', 'Scheduled Oct 14, 13:30', 'Explained billable rate: $125/h, 1h minimum'],
      transcript: [['member', 'Could someone mount the new TV in the media room? It’s 85 inches.'], ['ai', 'Happy to arrange it. Your complimentary hours for October are used, so this visit would be billed at $125 per hour (one-hour minimum, then 15-minute increments). Tuesday 14 October at 13:30 is available — shall I book it?'], ['member', 'Yes, book it.'], ['ai', 'Done — Tuesday 14 October at 13:30. You’ll receive a reminder the day before.']] },
    { id: 'C-5008', channel: 'Call', member: null, from: '(214) 555-0187 · New caller', when: 'Yesterday', duration: '4m 05s', status: 'Handed off', reason: 'Prospective member — consultation booked for Esty.',
      summary: 'Prospective member in a 6,000 sq ft home asked about Signature membership. AI explained both tiers and booked a consultation with Esty.',
      actions: ['Created lead: Hannah Ross', 'Booked consultation Fri, Oct 10, 11:00 with Esty'],
      transcript: [['ai', 'Moda Management, this is the Moda concierge. How can I help?'], ['member', 'I’m interested in your membership — what’s the difference between the two?'], ['ai', 'Essential is $99 a month with an annual walk-through and an hour of handyman care each month. Signature is $499 with monthly walk-throughs, two hours of handyman care, and one dedicated point of contact. Would you like to meet Esty at your home to talk it through?'], ['member', 'Yes, Friday morning works.'], ['ai', 'Friday 10 October at 11:00 is booked. You’ll receive a confirmation by text.']] },
  ],
  estimates: [
    { id: 'E-1039', member: 'whitfield', title: 'Gutter clearing & downspout check', amount: 420, sent: 'Oct 6', status: 'Awaiting approval', lines: [['Gutter clearing — rear elevation', 260], ['Downspout flush & reseal', 95], ['Concierge on site (within visit)', 65]] },
    { id: 'E-1042', member: 'whitfield', title: 'Dishwasher gasket replacement & levelling', amount: 340, sent: 'Draft', status: 'Draft', lines: [['Door gasket (OEM)', 85], ['Labour — appliance technician, 1.5h', 195], ['Concierge on site, 1h minimum', 125]] },
    { id: 'E-1040', member: 'delacroix', title: 'Landscape lighting along drive', amount: 6450, sent: 'Oct 3', status: 'Awaiting approval', lines: [['Fixtures (14) & transformer', 3980], ['Installation & trenching', 2220], ['Concierge oversight', 250]] },
    { id: 'E-1041', member: 'ashby', title: 'Gallery wall picture lighting', amount: 2860, sent: 'Sep 29', status: 'Approved', lines: [['Picture lights (6)', 1740], ['Electrician', 870], ['Concierge oversight', 250]] },
    { id: 'E-1038', member: 'hartley', title: 'Garage door opener replacement', amount: 1120, sent: 'Sep 18', status: 'Declined', lines: [['Opener unit', 640], ['Installation', 480]] },
  ],
};
