import assert from 'node:assert/strict';
import { createServer } from 'vite';
const server=await createServer({server:{middlewareMode:true}});
const {inCurrentMonth,membershipLength,nextService,clientContext,intakeCommunications}=await server.ssrLoadModule('/src/lib/crm.ts');
assert.equal(inCurrentMonth('2026-10-01T04:59:00Z',new Date('2026-09-30T20:00:00Z')),true);
assert.equal(inCurrentMonth('2026-10-01T05:00:00Z',new Date('2026-09-30T20:00:00Z')),false);
assert.equal(membershipLength('2023-04-01',new Date('2026-09-30')), '3 years, 5 months');
const requests=[{id:'past',status:'scheduled',appointmentConfirmation:{scheduledStart:'2026-09-01'}},{id:'canceled',status:'canceled',appointmentConfirmation:{scheduledStart:'2026-10-01'}},{id:'next',status:'scheduled',appointmentConfirmation:{scheduledStart:'2026-10-02'}},{id:'tentative',status:'scheduling_requested',appointmentRequest:{requestedWindowStart:'2026-10-01'}}];
assert.equal(nextService(requests,new Date('2026-09-30')).id,'next');
assert.equal(intakeCommunications([{id:'r',channel:'portal'}],[]).length,0);
const c=clientContext({properties:[{homeownerId:'a',preferredVendorIds:['v1']}],requests:[{homeownerId:'a',status:'new',suggestedVendorId:'v3',vendorAssignment:{vendorId:'v2'}}],vendors:[{id:'v1'},{id:'v2'},{id:'v3'}],communications:[{homeownerId:'b',occurredAt:'2026-10-01'},{homeownerId:'a',occurredAt:'2026-09-01'}]},'a');
assert.deepEqual(c.providers.map(x=>x.id),['v1','v2']);
assert.equal(c.lastContact.occurredAt,'2026-09-01');
console.log('PASS: CT month boundaries, membership tenure, confirmed future services, contact isolation, preferred/approved providers.');
await server.close();
